### ISSUE TITLE
Modify the `fetch-metadata-and-generate-opts-json` workflow to fetch the workflow dynamically from Sharepoint

### ISSUE THREAD

**Issue by AishaHassen** [OpenFn/msf-lime-mosul#53]
## Background, context, and business value
In issue #47 we implemented a workflow to use a **stubbed** json of sharepoint output for the **lime-metadata** file. In this issue we will implement a logic to `get` the metadata file from sharepoint and use it in the rest of the workflow.

## The specific request, in as few words as possible
1. Modify the `Get metadata file from Sharepoint` job
Currently this job is hardcoding the values for `state.option_sets_xls_data` and `state.f01_mphss_baseline_xls`, instead it should:
* Fetch the metadata file from sharepoint using the following API endpoints:
```
1. https://graph.microsoft.com/v1.0/sites/root // get site-id = "openfn-msf-test"
2. https://graph.microsoft.com/v1.0/sites/{site-id}/drives // get drives for that site-id = msf-metadata
3. https://graph.microsoft.com/v1.0/sites/{site-id}/drives/{drive-id}/root/children  // get children for that drive and find Lime Metadata file and get the id for that file
4. https://graph.microsoft.com/v1.0/sites/{site-id}/drives/{drive-id}/items/{file-id}/workbook/worksheets  // using site-id, drive-id and file id, get a list of worksheets in that file id
5. https://graph.microsoft.com/v1.0/sites/{site-id}/drives/{drive-id}/items/{item-id}/workbook/worksheets/{worksheet-id}/usedRange // for each of the worksheet names that match the list below get the content of the worksheet and store in state
```
* The following are the list of worksheets that we are interested in this workflow:
1. F01-MHPSS Baseline
2. F03-mhGAP Baseline
3. F02-MHPSS Follow-up
4. F04-mhGAP Follow-up
5. F05-MHPSS Closure
6. OptionSets

* After fetching each of the above sheets, store them in a state object with naming that is a camel case versions of the sheet names. E.g this sheet name "F01-MHPSS Baseline" would turn to `f01_mhpss_baseline_xls`

2. Modify the `Map metadata file to option-set Json format` job
* Currently this job is only handling the json object conversion of `state.f01_mhpss_baseline`. Modify this job to also handle the newly added sheets(2. F03-mhGAP Baseline, F02-MHPSS Follow-up, F04-mhGAP Follow-up,  F05-MHPSS Closure)
* Modify the job that created the main `json` object, to also include the new sheets.
{
"option_sets":  {...contents of state.option_sets...},
"f01_mphss_baseline": {...contents of state.f01_mphss_baseline..}
"f02_mhpss_follow_up": {...contents of state.f02_mhpss_follow_up...}
.
.
.
}

### Expected data size
The metadata XLS file is 2.2MB

## state.json
`{}`

### Creds

Sign in to openfn's sharepoint account using your email address

## Toggl 
MSF 2024

**Comment by AishaHassen** [comment]
hey @mtuchi this spec is ready for you. 

I'm not able to see your implementation of #47 so i've created this spec as a continuation of that issue assuming that the implementation follow what is exactly on the spec. Please review it and let me know if you have any questions. 

FYI: @aleksa-krolls

**Comment by mtuchi** [comment]
I have modify the auto generate step in #47 to include the mentioned sheet name, See #54

**Comment by mtuchi** [comment]
@aleksa-krolls i am done with the  changes you can proceed testing the [workflow on app]( https://app.openfn.org/projects/cd92dd57-9a3c-4318-bdcb-f57a386cf811/runs/a7eb8882-1200-4a90-9009-fa3baec9aa01?step=92438a07-b14c-400b-94f2-037a5d09853c)
